name: Run tests

on:
  push:
    branches: [ main, dev, pg_tests ]
  pull_request:
    branches: [ main, dev, pg_tests ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9, "3.10" ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Install NeuroML etc.
      run: |

        pip install pyneuroml pyelectro
        pip install neuron

    - name: Get models
      run: |
      
        mkdir Standardised_MD_Script/HayModel
        git clone https://github.com/OpenSourceBrain/L5bPyrCellHayEtAl2011.git
        cp L5bPyrCellHayEtAl2011/neuroConstruct/generatedNeuroML2/*ml Standardised_MD_Script/HayModel
      
        mkdir Standardised_MD_Script/BahlModel
        git clone https://github.com/OpenSourceBrain/BahlEtAl2012_ReducedL5PyrCell.git
        cp BahlEtAl2012_ReducedL5PyrCell/NeuroML2/*ml Standardised_MD_Script/BahlModel

        
        git clone https://github.com/sanjayankur31/Human-L2-3-Cortical-Microcircuit
        git checkout feat/neuroml
        mv Human-L2-3-Cortical-Microcircuit Standardised_MD_Script/Yao_2022_Model

        find .

    - name: Test generation
      run: |

        cd Standardised_MD_Script

        ./run-script.sh

    - name: Final version info
      run: |
        pip list
        env
